/**
 * MAIN.GS
 * Entry Point
 */

// This function handles all HTTP GET requests (when someone visits the Web App URL)
function doGet(e) {
  // --- ROUTE 1: ADMIN PANEL ---
  // Checks if the URL has "?page=admin" at the end.
  // Example: script.google.com/.../exec?page=admin
  if (e && e.parameter && e.parameter.page === 'admin') {
    // Serves the 'Admin_QR.html' file (the QR Display screen)
    return HtmlService.createHtmlOutputFromFile('Admin_QR') 
        .setTitle('Admin Panel') // Sets the text in the browser tab
        .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL) // Allows the app to be embedded in iframes
        .addMetaTag('viewport', 'width=device-width, initial-scale=1'); // Ensures mobile responsiveness
  }

  // --- ROUTE 2: STUDENT APP (Default) ---
  // If the "page" parameter is missing or different, serve the Student Entry App ('index.html')
  var template = HtmlService.createTemplateFromFile('index');
  
  var qrCodeVal = "";
  // Check if the URL contains the security token "?code=..."
  // This is generated by the QR code on the Admin screen
  if (e && e.parameter && e.parameter.code) { 
    qrCodeVal = e.parameter.code;
  }
  
  // Inject the extracted token into the HTML template.
  // In 'index.html', this replaces "<?= serverQrCode ?>" with the actual value.
  template.serverQrCode = qrCodeVal;

  // Render the template and return the HTML to the user
  return template.evaluate()
      .setTitle('Foundation Attendance Entry')
      .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL)
      .addMetaTag('viewport', 'width=device-width, initial-scale=1');
}